@url_dev = http://localhost:3000/v1/api

### Sign Up
POST {{url_dev}}/logout
Content-Type: application/json
x-api-key: f2002b1080575197ba360bd5d9d1b3fb3fff1eee593054bb9b0796eafcde73d3
x-client-id: 685f9fe67084881f53400152
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODVmOWZlNjcwODQ4ODFmNTM0MDAxNTIiLCJlbWFpbCI6InRlc3RzaG9wMDFAZ21haWwuY29tIiwiaWF0IjoxNzUxMjg2MjQ5LCJleHAiOjE3NTE0NTkwNDl9.o3Z8Wspw6F4z-pHdAmpEkbahPnIkSfacqxfNHp2Z3gVern4WkGKEcP0HfZPg99xZviEsapuwrrGUX0uPdYf7F1SiKMUpzk9OzVK1tGb1iJozYAlinR5ZgeB9pthM9fxUocGxQU39JNzzSXOwn_RRlN5juM4AMe__SXoo707dpNfgtxa0o4G4XZ128ElqGummZFb4DYojibuh7vNWO6HtXiL8z2SaGN89HWe7oiERGy-F4m0cSY93G4tif2X-v4kMtVDqDy2VpE3p7iYt-1GLXnAbWkJoz2bKxrp-5nLjhtGkoG-iVKoO8GEVqIMTKTlqeF2Dq0e6wx6LwH3qs8Nk17TRLPq4Rnh9QKQDFMecCioR1I5lnC7noNLblfWRO3iGxQI2DW32RR2qeDjaNZFzRY5D-9Pow3C19yf0kUCkQfockdnikd6JhVqXoSJwN4BjtDMT2vUJfHLheYF2rYh-f6TxVnUwgP3GwGdZ5gHiGk2TRskN7wnZFsQFtEbUo7HL2wDpSgVAEY-qIMD9GCbzvaPIAew8KXBwemAxJZZrk4r9IhgXAHwFGGV7I93usZn9b2t40VEWne5JE3ev-O5aG_4fWl3I83c4Kk9aRBc8XXobuhy6HbkbHEDyGiCNhT8bZ_E17c7ldzihXcKsmjTT5QcgUTcQUWjxzDn3OIigFM8

{

}